name: Push File

on:
  workflow_dispatch:  # Manually start a workflow
  push:

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Mark test file
      run: |-
        echo $GITHUB_SHA > test02.md
        echo $GITHUB_SHA > test03.md

    - name: Ignore unchanged file
      uses: Jason2866/copy_file_to_another_repo_action@development
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test01.md'
        destination_repo: 'Jason2866/release-test'

    - name: Push changed file
      uses: Jason2866/copy_file_to_another_repo_action@mdevelopment
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test02.md'
        destination_repo: 'Jason2866/release-test'

    - name: Check custom commit message
      uses: Jason2866/copy_file_to_another_repo_action@development
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test03.md'
        destination_repo: 'Jason2866/release-test'
        commit_message: 'A custom message.'
